# Generated by Django 2.0.1 on 2018-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20180408_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
