# Generated by Django 2.0.1 on 2018-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0004_auto_20180408_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_categoria',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la categoria del lugar'),
        ),
    ]
