# Generated by Django 2.0.1 on 2018-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_auto_20180408_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
