# Generated by Django 2.0.1 on 2018-04-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0006_lugar_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='fotos',
            field=models.ManyToManyField(blank=True, null=True, to='lugares.Foto_lugar'),
        ),
    ]
