# Generated by Django 2.0.1 on 2018-04-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0007_auto_20180408_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='lugares.Foto_lugar'),
        ),
    ]
