# Generated by Django 2.0.1 on 2018-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0009_auto_20180410_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugartable',
            name='es_lugar_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
