# Generated by Django 2.0.1 on 2018-05-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0011_auto_20180410_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugartable',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calificaciones.CalificacionTable'),
        ),
    ]
