# Generated by Django 2.0.1 on 2018-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='tipo_calificacion',
            field=models.CharField(blank=True, choices=[('Usuario', 'lugar'), ('Lugar', 'lugar'), ('Opinion', 'opinion')], max_length=255, null=True),
        ),
    ]
