# Generated by Django 2.0.1 on 2018-04-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_calificacion_tipo_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_calificacion',
            field=models.CharField(blank=True, choices=[('Usuario', 'usuario'), ('Lugar', 'lugar'), ('Opinion', 'opinion')], max_length=255, null=True),
        ),
    ]
