# Generated by Django 2.0.1 on 2018-04-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
        ('calificaciones', '0004_auto_20180408_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calificacion',
            new_name='CalificacionTable',
        ),
    ]
