version: '3'

services:

  db:
      image: postgres

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmincont
      ports:
        - "8004:80"
      depends_on:
      - db
      environment:
        - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
        - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"



  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    depends_on:
      - db

