# Generated by Django 2.0.1 on 2018-04-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
        ('lugares', '0009_auto_20180410_1446'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='PersonaTable',
        ),
    ]
