# Generated by Django 2.0.1 on 2018-04-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_auto_20180410_2005'),
        ('accounts', '0003_personatable_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatable',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_persona', to='calificaciones.CalificacionTable'),
        ),
    ]
