# Generated by Django 2.0.1 on 2018-03-21 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('lugares', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_opinion', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calificaciones.Calificacion')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugares.Lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Persona')),
            ],
        ),
    ]
