# Generated by Django 2.0.1 on 2018-05-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0002_auto_20180410_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniontable',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
